# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FDJChallenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
   pod 'Kingfisher', '~> 7.2'

  # Pods for FDJChallenge

  target 'FDJChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FDJChallengeUITests' do
    # Pods for testing
  end

end
